source "https://rubygems.org"

# Specify your gem's dependencies in quant.gemspec.
gemspec

gem "puma"

gem "pg"

gem "propshaft"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
